import type { ThemeTokens } from './store'

export interface Preset {
  name: string
  description: string
  tokens: ThemeTokens
}

export const presets: Preset[] = [
  {
    name: 'Classic',
    description: 'The canonical neo brutalism look',
    tokens: {
      borderWidth: 3,
      borderColor: '#000000',
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      shadowColor: '#000000',
      borderRadius: 0,
      bgColor: '#FFFDF5',
      surfaceColor: '#FFFFFF',
      textColor: '#000000',
      primaryColor: '#FFD23F',
      secondaryColor: '#FF6B6B',
      dangerColor: '#FF4444',
      fontDisplay: 'Syne',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      fontMono: 'Space Mono',
      headingWeight: 700,
    },
  },
  {
    name: 'Vibrant',
    description: 'Bold pop-art energy',
    tokens: {
      borderWidth: 4,
      borderColor: '#000000',
      shadowOffsetX: 8,
      shadowOffsetY: 8,
      shadowBlur: 0,
      shadowColor: '#000000',
      borderRadius: 0,
      bgColor: '#1A1A2E',
      surfaceColor: '#16213E',
      textColor: '#FFFFFF',
      primaryColor: '#E94560',
      secondaryColor: '#0F3460',
      dangerColor: '#FF6B6B',
      fontDisplay: 'Bebas Neue',
      fontHeading: 'Plus Jakarta Sans',
      fontBody: 'DM Sans',
      fontMono: 'JetBrains Mono',
      headingWeight: 700,
    },
  },
  {
    name: 'Soft',
    description: 'Muted, approachable neo brutalism',
    tokens: {
      borderWidth: 2,
      borderColor: '#333333',
      shadowOffsetX: 4,
      shadowOffsetY: 4,
      shadowBlur: 2,
      shadowColor: '#333333',
      borderRadius: 4,
      bgColor: '#F5F0EB',
      surfaceColor: '#FFFFFF',
      textColor: '#222222',
      primaryColor: '#88D498',
      secondaryColor: '#74B9FF',
      dangerColor: '#FF7675',
      fontDisplay: 'Archivo Black',
      fontHeading: 'Outfit',
      fontBody: 'Inter',
      fontMono: 'Space Mono',
      headingWeight: 800,
    },
  },
  {
    name: 'Dark',
    description: 'High contrast, dark mode',
    tokens: {
      borderWidth: 3,
      borderColor: '#FFFFFF',
      shadowOffsetX: 5,
      shadowOffsetY: 5,
      shadowBlur: 0,
      shadowColor: '#FFFFFF',
      borderRadius: 0,
      bgColor: '#0A0A0A',
      surfaceColor: '#1A1A1A',
      textColor: '#FFFFFF',
      primaryColor: '#FFD23F',
      secondaryColor: '#FF6B6B',
      dangerColor: '#FF4444',
      fontDisplay: 'Syne',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      fontMono: 'Space Mono',
      headingWeight: 700,
    },
  },
  {
    name: 'Minimal',
    description: 'Clean black and white',
    tokens: {
      borderWidth: 2,
      borderColor: '#000000',
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      shadowBlur: 0,
      shadowColor: '#000000',
      borderRadius: 0,
      bgColor: '#FFFFFF',
      surfaceColor: '#F5F5F5',
      textColor: '#000000',
      primaryColor: '#000000',
      secondaryColor: '#666666',
      dangerColor: '#CC0000',
      fontDisplay: 'Archivo Black',
      fontHeading: 'Public Sans',
      fontBody: 'Inter',
      fontMono: 'JetBrains Mono',
      headingWeight: 900,
    },
  },
  {
    name: 'Cyber',
    description: 'Neon cyber-brutalism',
    tokens: {
      borderWidth: 3,
      borderColor: '#00FF41',
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowBlur: 0,
      shadowColor: '#00FF41',
      borderRadius: 0,
      bgColor: '#0D0208',
      surfaceColor: '#1A0A1E',
      textColor: '#00FF41',
      primaryColor: '#FF00FF',
      secondaryColor: '#00FF41',
      dangerColor: '#FF0040',
      fontDisplay: 'Syne',
      fontHeading: 'Space Grotesk',
      fontBody: 'Space Mono',
      fontMono: 'Space Mono',
      headingWeight: 700,
    },
  },
]
